# Cloudflare Pages 配置
name = "sub-store-frontend"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"
cwd = "frontend"
destination = "dist"

[build.environment_variables]
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"
