name = "xui-bridge-proxy"
main = "src/index.js"
compatibility_date = "2023-12-01"

[env.production]
name = "xui-bridge-proxy"
route = { pattern = "bridge.senma.io/*", zone_name = "senma.io" }

[env.production.vars]
BRIDGE_SERVER_URL = "http://141.11.91.40:3002"
BRIDGE_DOMAIN = "bridge.senma.io"
